### ISSUE TITLE
Getting error while trying to use snaptwink 

### ISSUE THREAD

**Issue by Lucky056** [JReverse/SnapTwink#4] opened 2021-12-09 04:04 UTC
I have been getting [this error](https://nekobin.com/biqimawisa)
I even tried to create SnapTwink folder since it said no directory or folder exists. But don't know how to fix the permission issue

**Comment by describe19** [comment] 2021-12-09 12:44
+1. The app never requests storage permissions.

**Comment by JReverse** [comment] 2021-12-09 14:30
@describe19 @Lucky056 wat Android Version you guys on 11 or 12?

**Comment by Lucky056** [comment] 2021-12-09 14:35
Android 11 for me

**Comment by describe19** [comment] 2021-12-09 18:32
I'm on 12

**Comment by Lucky056** [comment] 2021-12-10 11:00
@JReverse I think you should try adding these in Android xml

<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

**Comment by JReverse** [comment] 2021-12-11 00:28
[SnapTwink Test 1.zip](https://github.com/JReverse/SnapTwink/files/7696092/SnapTwink.Test.1.zip)

Test this @Lucky056  @describe19 lmk

**Comment by describe19** [comment] 2021-12-11 00:50
> [SnapTwink Test 1.zip](https://github.com/JReverse/SnapTwink/files/7696092/SnapTwink.Test.1.zip)
> 
> Test this @Lucky056 @describe19 lmk

Same issue

https://pastebin.com/raw/fu1ALX0u

**Comment by Lucky056** [comment] 2021-12-11 03:23
Still the same @JReverse. Doesn't works for me either. The app should ideally request storage permission but it doesn't

**Comment by JReverse** [comment] 2021-12-11 04:47
@Lucky056 I don't think you know what you're talking about lol its a GUI-LESS App you must go into settings and do it manually there's no invoking lol

**Comment by Lucky056** [comment] 2021-12-11 04:55
@JReverse well there's no option to enable it manually in Android 11. Like I said android 11&12 have scoped storage so.. Please refer to snaptrap repo. It works very well. And i assume it is kinda same like snaptwink

**Comment by JReverse** [comment] 2021-12-11 05:06
@Lucky056 WTF you talking about bro go to settings then go to apps and select the APP and give permissions i can do it on 12 so you can do it on 11....

**Comment by Lucky056** [comment] 2021-12-11 05:08
JReverse same issue exists even after I manually gave the app storage permissions!

**Comment by JReverse** [comment] 2021-12-11 05:09
@Lucky056 i can't reproduce and i'm using LSposed me and my friend have been using this privately for quite some time.

**Comment by Lucky056** [comment] 2021-12-11 05:10
> @Lucky056 i can't reproduce and i'm using LSposed me and my friend have been using this privately for quite some time.


I'll just send you screenshot, you can check mate! Idk why this issue occurs. I'm on lsposed too. Even enabled storage from settings. Issue still persists

**Comment by Lucky056** [comment] 2021-12-11 05:10
![Uploading Screenshot_20211211-103803.png…]()

**Comment by Lucky056** [comment] 2021-12-11 05:26
@JReverse https://nekobin.com/duxajobiwi
Check the logs after restarting I get this issue.
Even after I created a folder in. /emulated/0 it still says file not found.

Could you just mention all the steps on how to install snaptwink for once? Or send a screen recording. That would make it easier. So we could know if we are doing something wrong

**Comment by JReverse** [comment] 2021-12-11 06:09
[SnapTwinkT2.zip](https://github.com/JReverse/SnapTwink/files/7696539/SnapTwinkT2.zip)
@Lucky056 in setting give manage file perms try this should work A11 idk about 12 tho,

**Comment by Lucky056** [comment] 2021-12-11 07:37
@JReverse given all the permissions. Still the same. Attaching screenshot along 
https://imgur.com/a/zzliJr4

**Comment by Lucky056** [comment] 2021-12-11 07:49
I even uninstalled snaptwink and reinstalled it again. The issue still exists. Gave permission did everything. Not sure what's causing the issue.

**Comment by describe19** [comment] 2021-12-11 13:08
Yeah I'm still seeing no write access to home directory in logs. Even after manually granting perms. Tried both tests. I have pixel 6 (oriole), android 12, using zygisk with lsposed zygisk 1.6.5.

**Comment by Lucky056** [comment] 2021-12-11 13:20
@describe19 same goes for me! No home folder write access. I have no idea about Java tho so can't say if it's related or not

**Comment by JReverse** [comment] 2021-12-12 03:05
It's something to do with Magisk or LSposed i can confirm because even my old one no longer works.

If you're using alpha / canary with new zygisk use the new zygisk LSPOSED. Other then that idrk

To confirm this is the issue
https://cdn.discordapp.com/attachments/710135977552773190/900177669747003433/kzg4ROcOxGmV.apk

Install snapchat 11.50.0.29 if it dosen't work thats the issue if it does then may be a snapchat change and ill look

**Comment by describe19** [comment] 2021-12-12 03:22
This works for me :D

**Comment by Lucky056** [comment] 2021-12-12 05:14
> This works for me :D
> 
> I see checking home folder permissions read=true, write=true. And it saves stories and snaps.

So ig that's where the issue was!? Let me check and confirm

**Comment by Lucky056** [comment] 2021-12-12 05:32
@describe19
Can confirm this works!

**Comment by JReverse** [comment] 2021-12-12 15:58
@Lucky056 @describe19 You didn't tell me what works the zygisk LSposed or the apk?

**Comment by Lucky056** [comment] 2021-12-12 19:04
@JReverse the apk works like @describe19 said the apk you sent had home directory read = true, write =true

I think snapchat changed something of how snaps would be saved.

**Comment by JReverse** [comment] 2021-12-14 06:43
[SnapTwinkTest3.zip](https://github.com/JReverse/SnapTwink/files/7709281/SnapTwinkTest3.zip)

Try this on Version: 11.57.0.35

Remember ALWAYS RELOGIN / UNISTALL APP (FORCE UPGRADE / DOWNGRADE = BANS)

**Comment by Lucky056** [comment] 2021-12-14 07:23
@JReverse okay I'll try this out

**Comment by Lucky056** [comment] 2021-12-14 11:40
@JReverse uninstalled snaptrap and installed cleared data gave permission aswell. Still the same. Also this version you gave doesn't asks for storage permissions and I can't even turn it on from settings. Even tried app manager still the same. There's no user permission. As usual the home directory read = true and write = False

**Comment by describe19** [comment] 2021-12-14 12:50
> @JReverse uninstalled snaptrap and installed cleared data gave permission aswell. Still the same. Also this version you gave doesn't asks for storage permissions and I can't even turn it on from settings. Even tried app manager still the same. There's no user permission. As usual the home directory read = true and write = False

Same here

**Comment by JReverse** [comment] 2021-12-15 06:07
@Lucky056 @describe19 Don't worry about storage perms the working one doesn't ask either
[SnapTwinkTest4.zip](https://github.com/JReverse/SnapTwink/files/7716826/SnapTwinkTest4.zip)

test this

**Comment by describe19** [comment] 2021-12-15 07:35
Still the identical behaviour. Not working.

**Comment by JReverse** [comment] 2021-12-15 07:44
@describe19 just cuz it says write disabled dosen't mean not working having u tried?

**Comment by JReverse** [comment] 2021-12-15 07:48
Closing this as no one is really providing info. that is useful and i don't have a device to fix.

**Comment by Lucky056** [comment] 2021-12-15 08:05
@JReverse well I have tried everything as you instructed. At this point not sure what or how to help more

**Comment by Lucky056** [comment] 2021-12-15 08:07
@JReverse no actually @describe19 was right idk the exact terminalogy but when it says write = False. The app says permission failed. But only when it is true it works.

**Comment by JReverse** [comment] 2021-12-15 08:10
https://github.com/JReverse/SnapTwink/releases

I provided another build here just keep looking here once in a while once i get a device ill 100% know.

It's something to do with how i compiled it thats all i know atm.

**Comment by Lucky056** [comment] 2021-12-15 13:35
@JReverse could be as you said or maybe snapchat did something within the app that causes the issue.

**Comment by Lucky056** [comment] 2022-01-03 12:55
@JReverse can you try making build for the new version now? Maybe it might work now?

**Comment by Lucky056** [comment] 2022-01-11 09:41
@JReverse could you send that discord snaptwink test version which you  sent? The one that was working

**Comment by JReverse** [comment] 2022-01-12 16:34
@Lucky056 ill rewrite this project when  oneplus 10 pro is out for now archiving it.

**Closed by JReverse** 2022-01-12 16:34 UTC
Labels: bug, help wanted, on-hold
